ALTER TABLE users    ADD COLUMN IF NOT EXISTS custom_status TEXT NOT NULL DEFAULT '';
ALTER TABLE channels ADD COLUMN IF NOT EXISTS slow_mode_seconds INTEGER NOT NULL DEFAULT 0;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '';
